apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: postgres-cluster
  name: postgres-cluster
  namespace: postgres
spec:
  clusterIP: None
  selector:
    app: postgres-cluster
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
    - name: repl
      port: 5433
      targetPort: 5433
  type: ClusterIP
status:
  loadBalancer: {}
